# Generated by Django 3.1.14 on 2025-10-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('image', models.ImageField(upload_to='student/')),
                ('dob', models.DateField()),
                ('courses', models.ManyToManyField(related_name='students', to='course.Course')),
            ],
        ),
    ]
