# Generated by Django 5.2.7 on 2025-10-16 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('published', models.DateField()),
                ('appropreiate', models.CharField(choices=[('Kids', '8'), ('adults', '+15')])),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.author')),
            ],
        ),
    ]
