# Generated by Django 5.2.7 on 2025-10-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='appropreiate',
            field=models.CharField(choices=[('under 8', '8'), ('8-15', '8-15'), ('adults', '+15')]),
        ),
    ]
